### ISSUE TITLE
Test with Python 3.4.4

### ISSUE THREAD

**Issue by caglartoklu** [caglartoklu/spyonde#14]

**Comment by caglartoklu** [comment]
it seems tokenizer module was different in Python 3.4.4 too, and not compatible with Python 3.6 and 3.7. We will need to another `if` for compatibility.

```
Spyonde started.
args:
  Namespace(files=['examples\\demo.py'], nbversion='3.7.4', overwrite=False)
Traceback (most recent call last):
  File "C:\Python34\Scripts\spyonde-script.py", line 9, in <module>
    load_entry_point('spyonde==0.1.0', 'console_scripts', 'spyonde')()
  File "c:\temp\spyonde\spyonde\spyondemain.py", line 950, in start_command_line

    convert_file(file_name, args_dict)
  File "c:\temp\spyonde\spyonde\spyondemain.py", line 855, in convert_file
    data = parse_cells(cells)
  File "c:\temp\spyonde\spyonde\spyondemain.py", line 624, in parse_cells
    assert isinstance(cells[0], list)
IndexError: list index out of range



Spyonde started.
args:
  Namespace(files=['examples\\simple1.py'], nbversion='3.7.4', overwrite=False)
Traceback (most recent call last):
  File "C:\Python34\Scripts\spyonde-script.py", line 9, in <module>
    load_entry_point('spyonde==0.1.0', 'console_scripts', 'spyonde')()
  File "c:\temp\spyonde\spyonde\spyondemain.py", line 950, in start_command_line

    convert_file(file_name, args_dict)
  File "c:\temp\spyonde\spyonde\spyondemain.py", line 855, in convert_file
    data = parse_cells(cells)
  File "c:\temp\spyonde\spyonde\spyondemain.py", line 624, in parse_cells
    assert isinstance(cells[0], list)
IndexError: list index out of range



Spyonde started.
args:
  Namespace(files=['examples\\simple2.py'], nbversion='3.7.4', overwrite=False)
Traceback (most recent call last):
  File "C:\Python34\Scripts\spyonde-script.py", line 9, in <module>
    load_entry_point('spyonde==0.1.0', 'console_scripts', 'spyonde')()
  File "c:\temp\spyonde\spyonde\spyondemain.py", line 950, in start_command_line

    convert_file(file_name, args_dict)
  File "c:\temp\spyonde\spyonde\spyondemain.py", line 855, in convert_file
    data = parse_cells(cells)
  File "c:\temp\spyonde\spyonde\spyondemain.py", line 624, in parse_cells
    assert isinstance(cells[0], list)
IndexError: list index out of range
```

here is the Python version that caused the log above:

```
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
